// Generated by CoffeeScript 1.11.1
var App, content, getApp, getCurrentPages;

import React from 'react';

content = {};

App = function(content) {};

getApp = function() {};

getCurrentPages = function() {};

module.exports = {
  App: App,
  getApp: getApp,
  getCurrentPages: getCurrentPages
};
