// Generated by CoffeeScript 1.11.1
import React from 'react'

import {
	Text,
  AppRegistry
} from 'react-native';

import wxas from 'weixin-app-sprite';

import config from './testApp/RN_app_config';

import routes from './testApp/RN_routes';

wxas.init(config, routes);

aa = React.createClass({


  render: function() {
    return <Text>dddddddddddddd</Text>
  }
});


AppRegistry.registerComponent('test', (function(_this) {
  return function() {
    return wxas.WXView;
  };
})(this));
