// Generated by CoffeeScript 1.12.1
module.exports = {
  root: 'app.js',
  rootConfig: 'app.json',
  rootWxss: 'app.wxss',
  pages: 'pages',
  varPrefix: 'R_$wxas$_',
  bindEvents: ['bindtouchstart', 'bindtouchmove', 'bindtouchcancel', 'bindtouchend', 'bindtap', 'bindlongtap'],
  catchEvents: ['catchtouchstart', 'catchtouchmove', 'catchtouchcancel', 'catchtouchend', 'catchtap', 'catchlongtap']
};
