// Generated by CoffeeScript 1.11.1
var Config, S, Template, Wxss, _, appConfig, appJs, appJson, appPath, appWxss, cssCode, defaultWindowConfig, fs, i, j, len, len1, outWxml, page, pageCode, pageConfig, pageFilePath, pageName, pagePath, path, ref, ref1, routes, tab, tabList, wxss;

fs = require('fs');

path = require('path');

S = require('string');

_ = require('underscore');

Config = require('./lib/config');

outWxml = require('./lib/wxml');

Wxss = require('./lib/Wxss');

Template = require('./lib/template');

appPath = "c:/dev/weixinapp/weixin-app-sprite-dev/test/testApp/";

appJs = fs.readFileSync(appPath + Config.root);

appJson = fs.readFileSync(appPath + Config.rootConfig);

appWxss = fs.readFileSync(appPath + Config.rootWxss);

appConfig = JSON.parse(appJson.toString());

fs.writeFileSync(appPath + "/RN_app_config.js", Template.createConfig(appJson.toString()));

defaultWindowConfig = {
  navigationBarBackgroundColor: '#000000',
  navigationBarTextStyle: 'white',
  navigationBarTitleText: '',
  backgroundColor: '#ffffff',
  backgroundTextStyle: 'dark',
  enablePullDownRefresh: false
};

defaultWindowConfig = _.extend({}, defaultWindowConfig, appConfig.window ? appConfig.window : {});

routes = {};

ref = appConfig.pages;
for (i = 0, len = ref.length; i < len; i++) {
  page = ref[i];
  pagePath = path.dirname(page);
  pageName = path.basename(page);
  pageFilePath = appPath + pagePath + '/' + pageName;
  pageCode = fs.readFileSync(pageFilePath + '.js');
  fs.writeFileSync((appPath + pagePath) + "/RN_" + pageName + ".js", Template.createPage(pageCode.toString(), pageName));
  wxss = null;
  if (fs.existsSync(pageFilePath + '.wxss')) {
    cssCode = fs.readFileSync(pageFilePath + '.wxss');
    wxss = new Wxss(pageFilePath + '.wxss');
  }
  outWxml(appPath + pagePath, pageName, wxss);
  if (fs.existsSync(pageFilePath + '.json')) {
    pageConfig = fs.readFileSync(pageFilePath + '.json');
    routes[page] = _.extend({}, defaultWindowConfig, JSON.parse(pageConfig.toString()));
  } else {
    routes[page] = defaultWindowConfig;
  }
  routes[page]['wxas_path'] = pagePath;
  if (tabList = (ref1 = appConfig.tabBar) != null ? ref1.list : void 0) {
    for (j = 0, len1 = tabList.length; j < len1; j++) {
      tab = tabList[j];
      if (tab.pagePath === page) {
        if (tab.text) {
          routes[page]['wxas_tabBar_text'] = tab.text;
        }
        if (tab.iconPath) {
          routes[page]['wxas_tabBar_iconPath'] = tab.iconPath;
        }
        if (tab.iconPath) {
          routes[page]['wxas_tabBar_selectedIconPath'] = tab.selectedIconPath;
        }
        routes['tab/' + page] = routes[page];
        delete routes[page];
        break;
      }
    }
  }
}

fs.writeFileSync(appPath + "/RN_routes.js", Template.createRoute(routes));
