// Generated by CoffeeScript 1.12.1
var S, classRegex, css, cssRegex, i, idRegex, importCmd, len, props, ref, ref1, style, tagRegex, value;

S = require('string');

cssRegex = /.+\{(\s*\w+\s*:\s*\w\s*;\s*)+\}/g;

cssRegex = /[^\{^\}]+\{[^\{^\}]+\}/g;

classRegex = /\.\w+\s*\{(\s*\w+\s*:\s*\w\s*;\s*)+\}/g;

tagRegex = /\w+\s*\{(\s*\w+\s*:\s*\w\s*;\s*)+\}/g;

idRegex = /#\w+\s*\{(\s*\w+\s*:\s*\w\s*;\s*)+\}/g;

idRegex = /#\w+\s*\{(\s*\w+\s*:\s*\w\s*;\s*)+\}/g;

importCmd = /@import\s*"\w+"/g;

css = ".ccc {\n    sdfsdf\n    a: 1\n    b:2;\n}\n\n.ccc , aa{\n    a: 1;\n    b:2;\n}\n\n.ccc aa, aa {\n    a: 1;\n    b:2;\n}\n\n\n\ntext {\n  text-align: ddd; \n  color: green;\n}\n\n#ccc #aaa {\n    a: 1;\n    b:2;\n}\n";

console.log(css.match(cssRegex));

console.log("text { a:1\n b: 2}".split(/\{|\}/));

console.log("\n\ntext \n\n .cc aa \n\n".match(/[^\s]+/g));

console.log("\n\ntext-align: 100px\n\n color: green;\n\n".match(/[\w-]+\s*:\s*[\w\d-]+/g));

style = "width: 30px; height:650px; ";

ref = style.split(';');
for (i = 0, len = ref.length; i < len; i++) {
  css = ref[i];
  if (S(css).isEmpty()) {
    continue;
  }
  ref1 = S(css).trim().s.split(/\s*:\s*/), props = ref1[0], value = ref1[1];
  console.log(props);
  console.log(value);
}
